/**
 * Demo/mock data for admin panel when Supabase is not configured or in demo mode.
 */
import type { ProductRow } from "@/lib/schema";
import type { SiteSettingsRow } from "@/lib/schema";
import type { PaymentGatewayRow } from "@/lib/schema";

const now = new Date().toISOString();

export const DEMO_PRODUCTS: ProductRow[] = [
  {
    id: "demo-1",
    created_at: now,
    updated_at: now,
    name_en: "Premium Dog Food 2kg",
    name_bn: null,
    slug: "premium-dog-food-2kg",
    description_en: "High quality dog food",
    description_bn: null,
    buying_price: 400,
    selling_price: 650,
    stock: 50,
    weight_kg: 2,
    sku: "DOG-001",
    category_slug: "dog-food",
    images: ["https://placehold.co/200x200?text=Dog+Food"],
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
    seo_tags: null,
    meta_og_image: null,
  },
  {
    id: "demo-2",
    created_at: now,
    updated_at: now,
    name_en: "Cat Treats 500g",
    name_bn: null,
    slug: "cat-treats-500g",
    description_en: "Delicious cat treats",
    description_bn: null,
    buying_price: 150,
    selling_price: 250,
    stock: 100,
    weight_kg: 0.5,
    sku: "CAT-001",
    category_slug: "cat-food",
    images: ["https://placehold.co/200x200?text=Cat+Treats"],
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
    seo_tags: null,
    meta_og_image: null,
  },
  {
    id: "demo-3",
    created_at: now,
    updated_at: now,
    name_en: "Pet Toy Bundle",
    name_bn: null,
    slug: "pet-toy-bundle",
    description_en: "Assorted pet toys",
    description_bn: null,
    buying_price: 200,
    selling_price: 350,
    stock: 75,
    weight_kg: 0.3,
    sku: "TOY-001",
    category_slug: "toys",
    images: ["https://placehold.co/200x200?text=Pet+Toys"],
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
    seo_tags: null,
    meta_og_image: null,
  },
];

export const DEMO_SITE_SETTINGS: Partial<SiteSettingsRow> = {
  id: "default",
  updated_at: now,
  logo_url: null,
  logo_dark_url: null,
  site_name_en: "City Plus Pet Shop",
  site_name_bn: null,
  tagline_en: "Your pet, our passion",
  tagline_bn: null,
  primary_color: "#0f172a",
  secondary_color: "#06b6d4",
  accent_color: "#f97316",
  font_family: null,
  button_style: null,
  navbar_links: [],
  footer_text_en: null,
  footer_text_bn: null,
  footer_links: [],
  copyright_text: null,
  social_links: [],
  address_en: "Mirpur 2, Borobag, Dhaka 1216",
  address_bn: null,
  phone: "+880 1643-390045",
  email: "info@citypluspetshop.com",
  whatsapp_number: null,
  hero_slider: [],
  side_banners: [],
  cta_buttons: [],
  popup_enabled: false,
  popup_content_en: null,
  popup_content_bn: null,
  popup_image_url: null,
  facebook_pixel_id: null,
  facebook_capi_token: null,
  google_analytics_id: null,
  google_tag_manager_id: null,
  auth_providers: null,
  default_meta_title: null,
  default_meta_description: null,
  default_og_image_url: null,
  homepage_blocks: null,
  delivery_inside_dhaka: 70,
  delivery_outside_dhaka: 130,
  free_delivery_threshold: 2000,
  terms_url: "/terms",
  privacy_url: "/privacy",
};

export const DEMO_PAYMENT_GATEWAYS: PaymentGatewayRow[] = [
  {
    id: "demo-cod",
    created_at: now,
    updated_at: now,
    gateway: "cod",
    is_active: true,
    display_name_en: "Cash on Delivery",
    display_name_bn: null,
    credentials_json: null,
  },
  {
    id: "demo-bkash",
    created_at: now,
    updated_at: now,
    gateway: "bkash",
    is_active: true,
    display_name_en: "bKash",
    display_name_bn: "বিকাশ",
    credentials_json: {},
  },
  {
    id: "demo-nagad",
    created_at: now,
    updated_at: now,
    gateway: "nagad",
    is_active: false,
    display_name_en: "Nagad",
    display_name_bn: "নগদ",
    credentials_json: {},
  },
  {
    id: "demo-sslcommerz",
    created_at: now,
    updated_at: now,
    gateway: "sslcommerz",
    is_active: false,
    display_name_en: "SSLCommerz",
    display_name_bn: null,
    credentials_json: {},
  },
];

export const DEMO_ORDERS = [
  { id: "ORD-001", customerName: "John Doe", email: "john@example.com", total: 1250, status: "delivered", createdAt: "2026-02-05T10:00:00Z" },
  { id: "ORD-002", customerName: "Jane Smith", email: "jane@example.com", total: 890, status: "processing", createdAt: "2026-02-05T11:30:00Z" },
  { id: "ORD-003", customerName: "Mike Johnson", email: "mike@example.com", total: 2100, status: "shipped", createdAt: "2026-02-04T09:15:00Z" },
];

export const DEMO_ANALYTICS_EVENTS = {
  events: [] as unknown[],
  counts: {} as Record<string, number>,
  lastReceivedByEvent: {} as Record<string, string>,
  diagnostics: { pixelConfigured: false, capiConfigured: false, warnings: [] as string[] },
};
