import { defineType, defineField, defineArrayMember } from "sanity";
import { blockContent } from "./blockContent";

export const productSchema = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "commerce", title: "Commerce" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "category" }],
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "brand",
      title: "Brand",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      group: "content",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "blockContent",
      group: "content",
    }),
    defineField({
      name: "price",
      title: "Price (BDT)",
      type: "number",
      group: "commerce",
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: "comparePrice",
      title: "Compare at Price (BDT)",
      type: "number",
      group: "commerce",
      description: "Original price for showing discount",
    }),
    defineField({
      name: "stock",
      title: "Stock Quantity",
      type: "number",
      group: "commerce",
      initialValue: 0,
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: "inStock",
      title: "In Stock",
      type: "boolean",
      group: "commerce",
      initialValue: true,
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "specs",
      title: "Specifications",
      type: "object",
      group: "content",
      options: { columns: 2 },
      fields: [
        { name: "weight", type: "string", title: "Weight" },
        { name: "flavor", type: "string", title: "Flavor" },
      ],
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "commerce",
      initialValue: false,
    }),
    defineField({
      name: "rating",
      title: "Rating (1-5)",
      type: "number",
      group: "content",
      validation: (Rule) => Rule.min(0).max(5),
    }),
    defineField({
      name: "videoUrl",
      title: "Video URL",
      type: "url",
      group: "content",
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      group: "seo",
    }),
    defineField({
      name: "keywords",
      title: "Keywords",
      type: "array",
      group: "seo",
      of: [{ type: "string" }],
    }),
  ],
  preview: {
    select: { title: "title", media: "images.0", price: "price" },
    prepare({ title, media, price }) {
      return {
        title: title ?? "Untitled",
        media,
        subtitle: price != null ? `৳${price}` : undefined,
      };
    },
  },
});
